name: Builder

on: push

env:
  MVN_PUBLISH_SASCHA_USER: ${{secrets.MavenUser}}
  MVN_PUBLISH_SASCHA_TOKEN: ${{secrets.MavenToken}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Execute Gradle build and publish
        run: chmod +x gradlew && ./gradlew build publish
